name: Deployment
on:
    push:
        branches:
            - master
jobs:
    Deploy-to-VPS:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: '20'
            - run: npm i
            - run: npm run build --if-present
              env:
                  CI: false
            - name: Copy folder content recursively to vps
              uses: garygrossgarten/github-action-scp@release
              with:
                  local: build/dist
                  remote: /var/www/portle-assignment
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
            - run: echo "🍏 This job's status is ${{ job.status }}."
